# .github/workflows/hacs.yml
name: HACS validation

on:
  push:
    branches: [main]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Pick ONE of the 2 lines below ↓↓↓
      # Stable release tag:
      - uses: hacs/action@22.5.0
      # ── or ── bleeding‑edge main:
      # - uses: hacs/action@main

        with:
          category: "integration"        # required for integrations
          # ignore: "hacs"              # optional space‑separated list of checks to skip
          # ignore: "brands"
